language: java
deploy:
  provider: heroku
  api_key:
    secure: tc6QQkTspNt29ZHJ+djckO3lBqcUMxfHyUSeTxfzsFeYIMBn6+qJesBoDzPmtPIGpDNth8M6KP9geU7/ek2Lm19qlf6VnXVJe9F9f2wI/kT1Oh/6rne6E93Ssmqo5lQvgo1jFbT4T4Ueyv9cO5wWW4oykfxJF5TSGKmXX5ulswzOjcUuSvH2/g+DZcZEe8nflCM6qyfPie76B52zkFhhgU8u63+CQSjIaDwsGaaFvqCqkHP7uixPPhUEX3cFzrAeqW/hvPhgBd2uMkbkgpfmSI3hFs/trJ8YIPKE/RP8RXTKBAwsDBa4FVouKKMbhtvPmkR3QXJkZMy8ut1NKh0Hazz9i87nqZDB9d7Bxymr6nSpYnSCrN2RyZOqDjm3SIdXUr7BxwGRVXP1xNvsSOBUsXUwWSOuKRkzao0ebiM5tNI3tjPJ6oyRAtv5VIlf+5GctjdJHfX9ikWwpYve2mbchg+8UilxO6i7HRUHjsObZe/PnoURhcZpP0Uuljn3dkU4oJKVYAym5a2IpRzREkn2IAIHnfbfXgD09tbaHyX/PHXylP/kLqveSnu/y/ib2EjHHO0NSItK5dwGnEX5Eo5iFyFMfuiIgcx53CfYtVYrQXnH8s/klprTuOmrzlO5pjrqNW6ifBY9bNYZmlHz+brzMc+ssjIyi+AFCd3KrT+GyCw=
  app: jl-tagomi-contact-management
